### ISSUE TITLE
find: function.c

### ISSUE THREAD

**Issue by aicsx** [ataraxialinux/netbsd-tools#1]
its ok but have error! for fast make it ok but i give view for real resolution. For now:

line 958 find/function.c 
---flags = entry->fts_statp->st_flags;
+++flags = entry->fts_statp;

**Comment by protonesso** [comment]
Check if it works by running it

**Comment by aicsx** [comment]
yes It work, but  I have to check the syntax

**Comment by protonesso** [comment]
Like options -name, -type? Can you show the screenshot? After that, make a
pull request ;)

2020年4月12日(日) 0:49 ax <notifications@github.com>:

**Comment by aicsx** [comment]
$ find /home/ax -name "*.c" -print
http://termbin.com/fa40

i cant screenshot tty now ... it's log.

**Comment by protonesso** [comment]
Put log. And you installed `find` in system?

2020年4月12日(日) 1:41 ax <notifications@github.com>:

**Comment by aicsx** [comment]
obviously yes

**Comment by protonesso** [comment]
Send log on pastebin

2020年4月12日(日) 1:58 ax <notifications@github.com>:

**Comment by aicsx** [comment]
I have not understood which , it's log ... you mean but I can reconfirm that it works an
that xargs...
other test example: 
~$ find . -type f -name "*.c" -print | xargs grep -l "proc" 
http://termbin.com/45j5

**Comment by protonesso** [comment]
Okay, close issue and make a pull request. Watching anime rn :p

2020年4月12日(日) 2:10 ax <notifications@github.com>:

**Comment by aicsx** [comment]
ok. pr send.

**Comment by protonesso** [comment]
```
./src/find/find: invalid option -- 'n'
./src/find/find: invalid option -- 'a'
./src/find/find: invalid option -- 'm'
./src/find/find: invalid option -- 'e'
```
